CREATE TABLE IF NOT EXISTS public."Articles"
(
    "articleId" INT NOT NULL PRIMARY KEY,
    "feedId" INT NULL DEFAULT 0,
    "subjects" SMALLINT NULL DEFAULT 0,
    "subjectId" INT NULL DEFAULT 0,
    "domainId" INT NULL DEFAULT 0,
    "score" SMALLINT NULL DEFAULT 0,
    "images" SMALLINT NULL DEFAULT 0,
    "filesize" DOUBLE PRECISION NULL DEFAULT 0,
    "linkcount" INT DEFAULT 0,
    "linkwordcount" INT DEFAULT 0,
    "wordcount" INT DEFAULT 0,
    "sentencecount" SMALLINT DEFAULT 0,
    "paragraphcount" SMALLINT DEFAULT 0,
    "importantcount" SMALLINT DEFAULT 0,
    "analyzecount" SMALLINT DEFAULT 0,
    "yearstart" SMALLINT NULL DEFAULT 0,
    "yearend" SMALLINT NULL DEFAULT 0,
    "years" VARCHAR(50) DEFAULT '',
    "datecreated" TIMESTAMP NULL,
    "datepublished" TIMESTAMP NULL,
    "relavance" SMALLINT NULL DEFAULT 0,
    "importance" SMALLINT NULL DEFAULT 0,
    "fiction" SMALLINT NULL DEFAULT 1,
    "domain" VARCHAR(50) NULL DEFAULT '',
    "url" VARCHAR(250) NULL DEFAULT '',
    "title" VARCHAR(250) NULL DEFAULT '',
    "summary" VARCHAR(250) NULL DEFAULT '',
    "analyzed" DOUBLE PRECISION DEFAULT 0,
    "visited" INT NOT NULL DEFAULT 0,
    "cached" BOOLEAN NULL DEFAULT FALSE,
    "active" BOOLEAN NULL DEFAULT FALSE,
    "deleted" BOOLEAN NULL DEFAULT FALSE
);
