CREATE TABLE [dbo].[Articles]
(
	[articleId] INT NOT NULL PRIMARY KEY, 
    [feedId] INT NULL DEFAULT 0, 
	[subjects] SMALLINT NULL DEFAULT 0,
	[subjectId] INT NULL DEFAULT 0,
	[domainId] INT NULL DEFAULT 0,
	[score] SMALLINT NULL DEFAULT 0,
    [images] SMALLINT NULL DEFAULT 0, 
	[filesize] FLOAT NULL DEFAULT 0,
    [linkcount] INT DEFAULT 0, 
    [linkwordcount] INT DEFAULT 0, 
    [wordcount] INT DEFAULT 0, 
    [sentencecount] SMALLINT DEFAULT 0, 
    [paragraphcount] SMALLINT DEFAULT 0,
    [importantcount] SMALLINT DEFAULT 0, 
	[analyzecount] SMALLINT DEFAULT 0,
    [yearstart] SMALLINT NULL DEFAULT 0, 
    [yearend] SMALLINT NULL DEFAULT 0, 
	[years] NVARCHAR(50) DEFAULT '',
    [datecreated] DATETIME NULL, 
    [datepublished] DATETIME NULL, 
    [relavance] SMALLINT NULL DEFAULT 0, 
    [importance] SMALLINT NULL DEFAULT 0, 
    [fiction] SMALLINT NULL DEFAULT 1, 
    [domain] NVARCHAR(50) NULL DEFAULT '', 
    [url] NVARCHAR(250) NULL DEFAULT '', 
    [title] NVARCHAR(250) NULL DEFAULT '', 
    [summary] NVARCHAR(250) NULL DEFAULT '',
	[analyzed] FLOAT DEFAULT 0,
    [visited] INT NOT NULL DEFAULT 0,
	[cached] BIT NULL DEFAULT 0, 
    [active] BIT NULL DEFAULT 0, 
    [deleted] BIT NULL DEFAULT 0
)