CREATE TABLE [dbo].[Chats]
(
    [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    [AppUserId] UNIQUEIDENTIFIER NOT NULL,
    [Title] NVARCHAR(128) NOT NULL,
    [Created] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    [Modified] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    [Status] INT NOT NULL DEFAULT 1, --0=deleted, 1=active
    CONSTRAINT [FK_Chats_AppUsers] FOREIGN KEY ([AppUserId]) REFERENCES [dbo].[AppUsers]([Id])
)
