CREATE TABLE [dbo].[JournalEntries]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    [JournalId] INT NOT NULL, 
    [Title] NVARCHAR(128) NOT NULL, 
    [Description] NVARCHAR(512) NOT NULL, 
    [Created] DATETIME2 NOT NULL DEFAULT GETUTCDATE(), 
    [Modified] DATETIME2 NOT NULL DEFAULT GETUTCDATE(), 
    [Status] INT NOT NULL DEFAULT 1
)
