CREATE TABLE IF NOT EXISTS public."Domains"
(
    "domainId" INT NOT NULL PRIMARY KEY,
    "domain" VARCHAR(64) NOT NULL,
    "lang" VARCHAR(6) NOT NULL DEFAULT 'en',
    "parentId" INT NOT NULL DEFAULT 0,
    "hastitle" BOOLEAN NOT NULL DEFAULT FALSE,
    "paywall" BOOLEAN NOT NULL DEFAULT FALSE,
    "free" BOOLEAN NOT NULL DEFAULT FALSE,
    "https" BOOLEAN NOT NULL DEFAULT FALSE,
    "www" BOOLEAN NOT NULL DEFAULT FALSE,
    "empty" BOOLEAN NOT NULL DEFAULT FALSE,
    "deleted" BOOLEAN NOT NULL DEFAULT FALSE,
    "type" INT NOT NULL DEFAULT -1,
    "type2" INT NOT NULL DEFAULT -1,
    "articles" INT NOT NULL DEFAULT 0,
    "inqueue" INT NOT NULL DEFAULT 0,
    "title" VARCHAR(128) NOT NULL DEFAULT '',
    "company" VARCHAR(64) NOT NULL DEFAULT '',
    "description" VARCHAR(255) NOT NULL DEFAULT '',
    "datecreated" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "dateupdated" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastchecked" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP -- last scraped a URL from the domain
);
