-- File: Functions/GetPathFromUrl.sql
CREATE OR REPLACE FUNCTION public."GetPathFromUrl"
(
	url TEXT,
	domain VARCHAR(255)
);
RETURNS TEXT
AS
BEGIN
	-- get path by removing all text to the left of the domain name (and removing the domain name too)
	DECLARE result TEXT = REPLACE(REPLACE(SUBSTRING(url, CHARINDEX(domain, url) + LEN(domain) + 1, LEN(url) - CHARINDEX(domain, url) + LEN(domain)), 'index.html', ''), 'index.php', '')
	
	--remove query string
	IF CHARINDEX('?', result, 1) > 1 BEGIN
		SET result = SUBSTRING(result, 1, CHARINDEX('?', result, 1) - 1)
	END
	
	-- next, remove lingering slashes
	IF LEN(result) > =1 AND LEFT(result, 1) = '/' SET result = RIGHT(result, LEN(result) - 1)--first slash
	IF LEN(result) > 1 AND RIGHT(result, 1) = '/' SET result = LEFT(result, LEN(result) - 1) --last slash

	-- next, check if file extension exists
	DECLARE reverse TEXT = REVERSE(result)
	DECLARE slash INT = CHARINDEX('/', reverse)
	IF(SUBSTRING(result, LEN(result) - 3, 1) = '.' OR SUBSTRING(result, LEN(result) - 4, 1) = '.') BEGIN
		-- next, reverse the result and find the last slash
		IF slash >= 1 BEGIN
			SET result = REVERSE(SUBSTRING(reverse, slash + 1, LEN(reverse) - slash))
		END ELSE BEGIN
			SET result = ''
		END
	END
	
	-- next, remove the last item in the path
	--SET reverse = REVERSE(result)
	--SET slash = CHARINDEX('/', reverse)
	--IF slash >= 4 BEGIN
	--	SET result = REVERSE(SUBSTRING(reverse, slash + 1, LEN(reverse) - slash))
	--END ELSE BEGIN
	--	SET result = ''
	--END

	-- finally, check if last item in path is too long to be part of path
	WHILE 1 = 1 BEGIN
		IF LEN(result) <= 1 BEGIN
			SET result = ''
			BREAK
		END
		SET reverse = REVERSE(result)
		SET slash = CHARINDEX('/', reverse)
		IF slash >= 20 BEGIN
			SET result = REVERSE(SUBSTRING(reverse, slash + 1, LEN(reverse) - slash))
		END ELSE BEGIN
			BREAK
		END
	END
	RETURN result
END

-- File: Functions/SplitArray.sql
CREATE OR REPLACE FUNCTION SplitArray 
 (
 text  varchar(8000)
 ,delimiter varchar(100) = ',' --default to comma delimited.
 );
RETURNS retTable TABLE 
 (
  Position  INT GENERATED BY DEFAULT AS IDENTITY
 ,valueInt INT 
 ,valueNum Numeric(18,3)
 ,value varchar(2000)
 );
AS
/*
********************************************************************************
Purpose: Parse values from a delimited string
  & return the result as an indexed table
Copyright 1996, 1997, 2000, 2003 Clayton Groom (<A href="mailto:Clayton_Groom@hotmail.com">Clayton_Groom@hotmail.com</A>)
Posted to the public domain Aug, 2004
06-17-03 Rewritten as SQL 2000 function.
 Reworked to allow for delimiters > 1 character in length 
 and to convert Text values to numbers
********************************************************************************
*/
BEGIN
 DECLARE w_Continue  INT
  ,w_StartPos  INT
  ,w_Length  INT
  ,w_Delimeter_pos INT
  ,w_tmp_int  INT
  ,w_tmp_num  numeric(18,3)
  ,w_tmp_txt   varchar(2000)
  ,w_Delimeter_Len SMALLINT
 if len(text) = 0
 begin
  SET  w_Continue = 0 -- force early exit
 end 
 else
 begin
 -- parse the original text array into a temp table
  SET  w_Continue = 1
  SET w_StartPos = 1
  SET text = RTRIM( LTRIM( text))
  SET w_Length   = DATALENGTH( RTRIM( LTRIM( text)))
  SET w_Delimeter_Len = len(delimiter)
 end
 WHILE w_Continue = 1
 BEGIN
  SET w_Delimeter_pos = CHARINDEX( delimiter
      ,(SUBSTRING( text, w_StartPos
      ,((w_Length - w_StartPos) + w_Delimeter_Len)))
      );
 
  IF w_Delimeter_pos > 0  -- delimeter(s) found, get the value
  BEGIN
   SET w_tmp_txt = LTRIM(RTRIM( SUBSTRING( text, w_StartPos 
        ,(w_Delimeter_pos - 1)) ))
   if isnumeric(w_tmp_txt) = 1
   begin
    set w_tmp_int = cast( cast(w_tmp_txt as numeric) as INT)
    set w_tmp_num = cast( w_tmp_txt as numeric(18,3))
   end
   else
   begin
    set w_tmp_int =  null
    set w_tmp_num =  null
   end
   SET w_StartPos = w_Delimeter_pos + w_StartPos + (w_Delimeter_Len- 1)
  END
  ELSE -- No more delimeters, get last value
  BEGIN
   SET w_tmp_txt = LTRIM(RTRIM( SUBSTRING( text, w_StartPos 
      ,((w_Length - w_StartPos) + w_Delimeter_Len)) ))
   if isnumeric(w_tmp_txt) = 1
   begin
    set w_tmp_int = cast( cast(w_tmp_txt as numeric) as INT)
    set w_tmp_num = cast( w_tmp_txt as numeric(18,3))
   end
   else
   begin
    set w_tmp_int =  null
    set w_tmp_num =  null
   end
   SELECT w_Continue = 0
  END
  INSERT INTO retTable VALUES( w_tmp_int, w_tmp_num, w_tmp_txt )
 END
RETURN
END
